### ISSUE TITLE
Add CSS to Contents section

### ISSUE THREAD

**Issue by SouKangC-school** [SouKangC-school/sp23-cse110-lab3#3]
**Task list**
- [ ] Add CSS to "Agenda for the Meeting"
- [ ] Add CSS to "Miscellaneous Comments & Questions"
- [ ] Add CSS to "Diagrams"

**Is your feature request related to a problem? Please describe.**
Possibly a problem dealing with diagram formatting

**Describe alternatives you've considered**
No alternative

**Additional context**
None
